apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "clamav.fullname" . }}
  name: {{ include "clamav.fullname" . }}
spec:
  ports:
  - name: {{ include "clamav.fullname" . }}
    port: {{ .Values.service.port }}
    targetPort: 10443
  selector:
    name: {{ include "clamav.fullname" . }}
