apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "clamav.fullname" . }}-mirror
  name: {{ include "clamav.fullname" . }}-mirror
spec:
  ports:
  - name: {{ include "clamav.fullname" . }}-mirror
    port: 80
    targetPort: 8080
  selector:
    name: {{ include "clamav.fullname" . }}-mirror
