
clamavNotify:
  resources:   
    requests:
      cpu: 200m
      memory: 1000M
    limits:
      cpu: 500m
      memory: 2000M
  volume:
    storageClass: standard
    size: 1

clamavHTTP:
  resources:
    # clamavHTTP.resources -- The resource requests and limits for the clamav-http service
    requests:
      cpu: 100m
      memory: 100M
      ephemeral-storage: "50M"
    limits:
      cpu: 400m
      memory: 200M
      ephemeral-storage: "100M"


clamav:
  scaling:
      minReplicas: 1
      maxReplicas: 1
  certificate:
    create: true
  resources:
    # clamav.resources -- The resource requests and limits for the clamav service
    requests:
      cpu: 200m
      memory: 1000M
      ephemeral-storage: "500M"
    limits:
      cpu: 800m
      memory: 2000M
      ephemeral-storage: "1000M"

mginxProxy:
  resources:
  requests:
    cpu: 100m
    memory: 200M
    ephemeral-storage: "50M"
  limits:
    cpu: 150m
    memory: 300M
    ephemeral-storage: "100M"
